import { Afacad_Flux } from 'next/font/google'
import "./globals.css";

import { Toaster } from "@/components/ui/toaster"
import { BusinessNameContext } from '@/context/BusinessNameContext';
import Header from '@/components/Header';

const Afacad = Afacad_Flux({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  display: 'swap'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Afacad.className}`}
      >
        <BusinessNameContext>
          <Header/>
          <Toaster />
          {children}
        </BusinessNameContext>
      </body>
    </html>
  );
}
